user = {"user_id": "TAX-000001-2026",
            "name": "Shubham Ratnakar Kamlaskar",
            "job_profile": "Tech Proffesional",
            "email": "shubham.kamlaskar@gmail.com",
            "phone": "9762402091",
            "dob": "19/12/1994",
            "pan":"EASLK7345F",
            "aadhar":"7896-7854-2589",
            "tax_regime": "New",
            "employment_type": "Salaried",
            "company": "Amphibius Technologies",
            "salary":"1895785",
            "deductions": "240000",
            "tax_liability": "120000",
            "tax_saved": "248887",
            "city": "Pune",
            "member_since": "December 19, 2025",
            "days_active": "45",
            "documents_len": "12",
            "subscription_plan": "Premium Annual Plan",
            "next_billing_date": "December 19, 2026",
            "preference": {'email_notifications': True,
                           'sms_alerts': True,
                           'two_factor': False,
                           'dark_mode': False}}